[project]
name = "cqlib-adapter"
description = "Cqlib adapter"
authors = [
    { name = "China Telecom Quantum Group Quantum Computing Team", email = "tianyan@chinatelecom.cn" },
]
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
dynamic = ["version", "dependencies"]
classifiers = [
    "Environment :: Console",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries"
]

keywords = [
    "cqlib",
    "cqlib adapter",
    "pennylane",
    "quantum circuit",
    "quantum computing",
    "quantum programming language",
    "quantum",
    "sdk",
]

[project.entry-points."pennylane.plugins"]
"cqlib.device" = "cqlib_adapter.pennylane_ext.device:CQLibDevice"

[tool.setuptools.packages.find]
where = ["."]
include = ["cqlib_adapter*"]

[tool.setuptools.package-data]
"cqlib_adapter.pennylane_ext" = ["cqlib_config.toml"]

[tool.setuptools.dynamic]
version = { file = "cqlib_adapter/VERSION.txt" }
dependencies = { file = "requirements.txt" }

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"